2023-09-27 22:16:03,054 : INFO : Line No. : 62 - Start of script execution
2023-09-27 22:16:03,056 : INFO : Line No. : 73 - Storage for processed data: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-27 22:16:03,056 : INFO : Line No. : 76 - Log file on imported documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv
2023-09-27 22:16:03,056 : INFO : Line No. : 79 - Source directory for documents: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/10_raw/doc2scan
2023-09-27 22:16:03,058 : ERROR : Line No. : 155 - Import tracking file </Users/swmoeller/python/2023/large_language_model/BrainGPT/logs/file_import_log.csv> is missing. Creating a new panda dataframe.
2023-09-27 22:16:03,062 : INFO : Line No. : 272 - Pandas Dataframe updated with files 'to be imported' or 'duplicated'.
2023-09-27 22:16:03,062 : INFO : Line No. : 288 - Possible file.extensions for document loader analyzed and list of extensions generated.
2023-09-27 22:16:13,462 : INFO : Line No. : 328 - Document Die Dritte Dimension - Martin Pfiffner.pdf loaded.
2023-09-27 22:16:13,483 : INFO : Line No. : 330 - Splitting of document <Die Dritte Dimension - Martin Pfiffner.pdf> done with <1404> chunks
2023-09-27 22:16:19,097 : INFO : Line No. : 328 - Document Bosch_Washing_Machine.pdf loaded.
2023-09-27 22:16:19,100 : INFO : Line No. : 330 - Splitting of document <Bosch_Washing_Machine.pdf> done with <105> chunks
2023-09-27 22:16:19,100 : INFO : Line No. : 328 - Document state_of_the_union.txt loaded.
2023-09-27 22:16:19,101 : INFO : Line No. : 330 - Splitting of document <state_of_the_union.txt> done with <42> chunks
2023-09-27 22:16:19,335 : INFO : Line No. : 328 - Document Regulierung_von_Large_Language_Models_in_DSA_und_AIA-E_-_beck-online.pdf loaded.
2023-09-27 22:16:19,336 : INFO : Line No. : 330 - Splitting of document <Regulierung_von_Large_Language_Models_in_DSA_und_AIA-E_-_beck-online.pdf> done with <22> chunks
2023-09-27 22:16:19,347 : WARNING : Line No. : 25 - Unable to connect optimized C data functions [No module named 'clickhouse_connect.driverc.buffer'], falling back to pure Python
2023-09-27 22:16:19,347 : WARNING : Line No. : 33 - Unable to connect ClickHouse Connect C to Numpy API [No module named 'clickhouse_connect.driverc.npconv'], falling back to pure Python
2023-09-27 22:16:19,424 : INFO : Line No. : 45 - Using python library for writing JSON byte strings
2023-09-27 22:16:19,498 : INFO : Line No. : 464 - No existing DB found in /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed, skipping load
2023-09-27 22:16:19,499 : INFO : Line No. : 476 - No existing DB found in /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed, skipping load
2023-09-27 22:16:19,806 : INFO : Line No. : 67 - message='Request to OpenAI API' method=post path=https://api.openai.com/v1/embeddings
2023-09-27 22:16:22,179 : INFO : Line No. : 67 - message='OpenAI API response' path=https://api.openai.com/v1/embeddings processing_ms=147 request_id=a210bf4b4aaa1b4c6be65e61065625db response_code=200
2023-09-27 22:16:22,285 : INFO : Line No. : 424 - Persisting DB to disk, putting it in the save folder: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
2023-09-27 22:16:22,295 : INFO : Line No. : 422 - End of script execution


2023-09-27 22:16:22,296 : INFO : Line No. : 424 - Persisting DB to disk, putting it in the save folder: /Users/swmoeller/python/2023/large_language_model/BrainGPT/data/25_processed
